### ISSUE TITLE
Clearbit issue

### ISSUE THREAD

**Issue by YmmurcBan** [SharadKumar97/OSINT-SPY#1]
Clearbit is not sending the verification code >:(

**Comment by SharadKumar97** [comment]
Are you asking about phone OTP verification?

**Comment by pretech86** [comment]
it siad no module called clearbit 

Traceback (most recent call last):
  File "osint-spy.py", line 1, in <module>
    from modules import *
  File "/root/Downloads/7-information gathering/OSINT-SPY/modules/__init__.py", line 4, in <module>
    from company_detail import *
  File "/root/Downloads/7-information gathering/OSINT-SPY/modules/company_detail.py", line 5, in <module>
    import clearbit
ImportError: No module named clearbit
