### ISSUE TITLE
No module named 'clearbit'

### ISSUE THREAD

**Issue by vikas623** [SharadKumar97/OSINT-SPY#24]
I tried the way that are suggested in closed issue but it does'nt work

Traceback (most recent call last):
  File "osint-spy.py", line 1, in <module>
    from modules import *
  File "/home/vikas/SSPT/OSINT-SPY/modules/__init__.py", line 2, in <module>
    from modules.company_detail import *
  File "/home/vikas/SSPT/OSINT-SPY/modules/company_detail.py", line 4, in <module>
    import clearbit
ModuleNotFoundError: No module named 'clearbit'

**Comment by blackjack417** [comment]
becoz he dosent put the clearbit module in module floder

**Comment by Sayam753** [comment]
Hi @vikas623 
Have you successfully installed the requirements and activated the environment?

**Comment by blackjack417** [comment]
> Hi @vikas623
> Have you successfully installed the requirements and activated the environment?

yes..... 
![Screenshot](https://user-images.githubusercontent.com/32001687/82533483-f783d800-9b60-11ea-869f-79f2de85a7e9.png)
![Screenshot_2](https://user-images.githubusercontent.com/32001687/82533560-25691c80-9b61-11ea-96da-39fcc05a9cdc.png)

**Comment by Sayam753** [comment]
Hi @blackjack417 
We have updated the codebase today. Can you try a similar search on the new code?

**Comment by blackjack417** [comment]
> Hi @vikas623
> Have you successfully installed the requirements and activated the environment?

yes..... 
![Screenshot](https://user-images.githubusercontent.com/32001687/82533483-f783d800-9b60-11ea-869f-79f2de85a7e9.png)
![Uploading Screenshot_2.png…]()

**Comment by blackjack417** [comment]
still i got same error sir

ImportError: No module named clearbit

**Comment by Sayam753** [comment]
Ohh. I think you are trying to find `clearbit` module in `modules` directory of the OSINT-SPY project. 
Rather it comes as a dependancy. If you have `pip` installed in your system, you can simply run
```bash
pip install -r requirements.txt
```
in root directory of the project. This will install all the dependancies(along with clearbit module) required to run `osint-spy.py` module.

**Comment by Sayam753** [comment]
@blackjack417 
One more thing, in your previous comment, you have attached a screenshot in which your `clearbit_api_key` and `shodan_api_key` is visible. Can you remove that screenshot so as your API keys are not globally visible?

**Comment by blackjack417** [comment]
thanks for responding sir,

      i successfully installed it but i dont have company email address
thats why i struck at middle of your tool.
can you teach me more things like this actually i trying to learn past
2years individually 1st time i got responds from you thank you very much
sir
can i keep in touch with you actually i requesting you.

**Comment by Sayam753** [comment]
Yes, why not!
Here is my email ID - sayamkumar049@gmail.com

**Comment by Sayam753** [comment]
Hi @vikas623 
Are you resolve this issue or is it still there?
Thanks

**Comment by ChrisD1976** [comment]
Hi, i am trying to install osint-spy into kali linux and keep gettin this error..
sudo pip install -r requirements.txt
[sudo] password for kali: 
Collecting certifi==2019.11.28
  Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.0/156.0 kB 1.1 MB/s eta 0:00:00
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 1.4 MB/s eta 0:00:00
Collecting clearbit==0.1.7
  Downloading clearbit-0.1.7.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in clearbit setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

im not sure what to do.

**Comment by puch-dev** [comment]
It's neccesary to downgrade setuptools:

pip install "setuptools<58.0.0"

After that, just install again requeriments.txt.

Source: https://stackoverflow.com/questions/72414481/error-in-anyjson-setup-command-use-2to3-is-invalid
