### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by connectnet** [SharadKumar97/OSINT-SPY#27]
```
import clearbit
ImportError: No module named clearbit
```

**Comment by Sayam753** [comment]
Hey @connectnet 
Can you make sure all the requirements have been installed successfully?
Thanks

**Comment by connectnet** [comment]
Yes, all requirements are installed.
```
python osint-spy.py
Traceback (most recent call last):
  File "osint-spy.py", line 2, in <module>
    from modules import (get_bitcoin_data, get_ciphers, heart_bleed,
  File "/OSINT-SPY/modules/__init__.py", line 2, in <module>
    from .company_detail import *
  File "/OSINT-SPY/modules/company_detail.py", line 3, in <module>
    import clearbit
ImportError: No module named clearbit
```

**Comment by Sayam753** [comment]
Hi @connectnet 
Thanks for checking this out. Just to test if things work, I cloned the repo and installed the requirements in a separate environment. I was able to successfully execute all the commands. 
So, can you make sure if you have activated the virtual environment where the requirements have been installed? And provide some additional OS details to reproduce this issue?
Thanks

**Comment by phenix-rising** [comment]
I am having a similar issue
python3 osint-spy.py
Traceback (most recent call last):
  File "/home/phenix_rising/OSINT-SPY/osint-spy.py", line 2, in <module>
    from modules import (get_bitcoin_data, get_ciphers, heart_bleed,
  File "/home/phenix_rising/OSINT-SPY/modules/__init__.py", line 2, in <module>
    from .company_detail import *
  File "/home/phenix_rising/OSINT-SPY/modules/company_detail.py", line 3, in <module>
    import clearbit
ModuleNotFoundError: No module named 'clearbit'

# When I explore the modules directory it doesnt seem to have a clearbit module
~/OSINT-SPY/modules
$ ls
bitcoin.py  company_detail.py  config.py  config.py.save  device_search.py  email_search.py  __init__.py  ip_enum.py  malware.py  __pycache__  ssl_scan.py  utils.py
