### ISSUE TITLE
OSINT-SPY Email search has issues with Fullcontact API. 

### ISSUE THREAD

**Issue by adgpt** [SharadKumar97/OSINT-SPY#9]
I've recently installed all the dependencies and have checked all the instructions as specified. 
However, while running the command: **python osint-spy.py --email <email address of the target>**, I'm getting the following error: 

```
root@kali:~/OSINT-SPY# python osint-spy.py --email <Email address of the target>
Traceback (most recent call last):
  File "osint-spy.py", line 53, in <module>
    fetchData(email_id)
  File "/root/OSINT-SPY/modules/email.py", line 8, in fetchData
    person = fc.person(email=email_id)
  File "/usr/local/lib/python2.7/dist-packages/fullcontact/fullcontact.py", line 36, in <lambda>
    method = lambda endpoint=endpoint, **kwargs: self.api_get(endpoint, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fullcontact/fullcontact.py", line 64, in api_get
    return requests.get(endpoint, params=kwargs, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 869, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
**requests.exceptions.InvalidHeader: Invalid return character or leading space in header: X-FullContact-APIKey**

```

Note: 

- I've tried rebooting the virtual machine. 
- I've tried running it in both NAT and Bridged networking mode. 
- There's a similar case where I get the output **Try Again** when I try running it on a domain. 

Please Help.

**Comment by jakuta-tech** [comment]
> leading space in header: X-FullContact-APIKey

on the last line shows you what is wrong.

Perhaps you need to get an API key ?

**Comment by BhavKaran** [comment]
Put email address of the target and try again. if this not work then You need to Register on [FullContact](https://dashboard.fullcontact.com/register) and click Generate new API key after that copy the API key and paste into **OSINT-SPY/modules/config.py** file & try **`python osint-spy.py --email <Email address of the target>`** again.

**Comment by SharadKumar97** [comment]
The codebase has been updated. Please do a git pull and try again.
